# Practical 10

In [1]:
#Q.1.1 Use python code to evaluate each of the following expression.
#a) 50 modulus 5 +11-(13+7)x10 /5
a= 50%5+11-(13+7)*10/5
print(a)
# b) 60x20 floor diviosion 3+15 modulus 3
b= 60*20//3+15%3
print(b)
# c) 2^7-2^3+8 floor division 4
print(2**7- 2**3 +8//4)


-29.0
400
122


In [2]:
#Q.1.2 list1[5,10,15,20,25,30] and list2 =[7,14,21,28,35,42]
#EVALUATE a) list1 +list2   
#         b) 3*list1         c)5*list2
list1=[5,10,15,20,25,30]
list2=[7,14,21,28,35,42]
a=list1+list2
b=3*list1
c=5*list2
print(a,"\n",b,"\n",c)

[5, 10, 15, 20, 25, 30, 7, 14, 21, 28, 35, 42] 
 [5, 10, 15, 20, 25, 30, 5, 10, 15, 20, 25, 30, 5, 10, 15, 20, 25, 30] 
 [7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42]


In [3]:
#Q.1.3 using python find the area of triangle whose base is 10 and height is15
b=10
h=15
A =(1/2)*h*b
print('area of triangle is ', A)

area of triangle is  75.0


In [4]:
#Q.2.1 using python construct the following matrices:

import numpy as np

# 1. Create an identity matrix of order 10 x 10
identity_matrix = np.eye(10)
print("Identity Matrix (10x10):")
print(identity_matrix)

# 2. Create a zero matrix of order 7 x 3
zero_matrix = np.zeros((7, 3))
print("\nZero Matrix (7x3):")
print(zero_matrix)

# 3. Create a ones matrix of order 5 x 4
ones_matrix = np.ones((5, 4))
print("\nOnes Matrix (5x4):")
print(ones_matrix)

Identity Matrix (10x10):
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

Zero Matrix (7x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix (5x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#Q.2.2 Write python code to find value the function f(x)=x^2+x (-5<=x<=5)


for x in range (-5,5):
    f=x**2+x
    print(f)


20
12
6
2
0
0
2
6
12
20


In [2]:
#Q.2.3write python program to find determinant of matrix 
# A=[ 1 0 5 ;2 1 6  ;3 4 0] and B=[ 2 5  ; -1 4]
import sympy as sy
sy.init_printing()
A=sy.Matrix([[1,0,5],[2,1,6],[3,4,0]])
B=sy.Matrix([[2,5],[-1,4]])
print('det(A)= ',A.det())
print("det(B) = ",B.det())

det(A)=  1
det(B) =  13


In [1]:
#Q.3a.1 Write Python program to estimate the value of the integral  integral 1 to 3 (1/x) dx using Simpson's (1/3)rd rule (n=8).

def f(x):
    return 1 / x

def simpsons_rule(a, b, n):
    if n % 2 != 0:
        raise ValueError("n must be an even number.")
    
    h = (b - a) / n
    sum_odd = sum(f(a + (2 * i + 1) * h) for i in range(n // 2))
    sum_even = sum(f(a + 2 * i * h) for i in range(1, n // 2))
    
    integral = (h / 3) * (f(a) + f(b) + 4 * sum_odd + 2 * sum_even)
    return integral

# Define the interval and number of subintervals
a = 1
b = 3
n = 8

# Calculate the integral using Simpson's (1/3)rd rule
result = simpsons_rule(a, b, n)
print(f"The estimated value of the integral is: {result}")


The estimated value of the integral is: 1.0987253487253485


In [4]:
#Q.3a.2 Write Python program to evaluate interpolated value f(2.7) of the given data f(2)=0.69315,f(2.5)=0.91629,f(3)=1.09861
def lagrange_interpolation(x, data_points):
    result = 0
    for i in range(len(data_points)):
        term = data_points[i][1]
        for j in range(len(data_points)):
            if i != j:
                term *= (x - data_points[j][0]) / (data_points[i][0] - data_points[j][0])
        result += term
    return result

# Given data points (x, f(x))
data_points = [(2, 0.69315), (2.5, 0.91629), (3, 1.09861)]

# Value to interpolate
x = 2.7

# Calculate the interpolated value at x = 2.7
interpolated_value = lagrange_interpolation(x, data_points)
print(f"The interpolated value of f(2.7) is: {interpolated_value}")



The interpolated value of f(2.7) is: 0.9941164


In [5]:
#Q.3b.1 Write Python program to obtained the approximate real root of x³ - 4x - 9= 0 by using Regula-falsi method.

def f(x):
    return x**3 - 4*x - 9

def regula_falsi(a, b, tol, max_iter):
    if f(a) * f(b) >= 0:
        print("The function has the same sign at the endpoints a and b.")
        return None

    for i in range(max_iter):
        # Calculate the false position
        c = a - (f(a) * (b - a)) / (f(b) - f(a))
        
        # Check if we found the root or if the interval is small enough
        if f(c) == 0 or abs(f(c)) < tol:
            return c

        # Update the interval
        if f(c) * f(a) < 0:
            b = c
        else:
            a = c
            
    # Return the approximation after the max iterations
    return c

# Initial guesses for the root
a = 2
b = 3

# Tolerance level and maximum iterations
tolerance = 1e-6
max_iterations = 100

# Calculate the root using Regula-Falsi method
root = regula_falsi(a, b, tolerance, max_iterations)

if root is not None:
    print(f"The approximate real root of the equation is: {root:.6f}")
else:
    print("The method did not converge.")


The approximate real root of the equation is: 2.706528


In [6]:
#Q.3b.2 Write Python program to estimate the value of the integral 0 to 1 cos(x)dx using Trape- zoidal rule (n=5).

import math

# Define the function to integrate
def f(x):
    return math.cos(x)

# Function to calculate the integral using Trapezoidal rule
def trapezoidal_rule(a, b, n):
    h = (b - a) / n
    integral = (f(a) + f(b)) / 2  # Initial value with the first and last terms
    
    for i in range(1, n):
        x = a + i * h
        integral += f(x)
    
    integral *= h
    return integral

# Define the interval [a, b] and number of subintervals n
a = 0
b = 1
n = 5

# Calculate the integral
result = trapezoidal_rule(a, b, n)
print(f"The estimated value of the integral is: {result:.6f}")


The estimated value of the integral is: 0.838664
