# Practical 3



In [7]:
#Q.1.1. write python code to test whether given number is divisible by 2 or 3 or 5
n= int(input("Enter the number: "))
if n%2==0 or n%3==0 or n%5==0:
    print("given number is divisible by 2 or 3 or 5")
else :
    print(" given number is not divisible by 2 or 3 or 5")


Enter the number: 30
given number is divisible by 2 or 3 or 5


In [12]:
#Q.1.2.Repeat the following string 11 times using the string operator '*' on python
# a. LATEX    b.MATLAB
a= "LATEX "
b= "MATLAB "
print(a*11)
print(b*11)

LATEX LATEX LATEX LATEX LATEX LATEX LATEX LATEX LATEX LATEX LATEX 
MATLAB MATLAB MATLAB MATLAB MATLAB MATLAB MATLAB MATLAB MATLAB MATLAB MATLAB 


In [13]:
#Q1.3. use python code to find sum of first thirty natural numbers
sum=0
for i in range(1,31):
    sum=sum+i
print(sum)

465


In [14]:
#Q.2.1. using python construct the following matrices
 #1)An identity matrix od order 10 x 10

import numpy as np
np.array(np.identity(10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
# 2) zero matrix of order 7 x 3

import numpy as np
np.zeros([7,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 3) Ones matrix of order 5 x 4
import numpy as np
np.ones([5,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#Q.2 using python, find the eigenvalues and corresponding eigenvectors of the matrix [3  -2 ;6 -4
import numpy as np

# Define the matrix
A = np.array([[3, -2],
              [6, -4]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Output the results
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 1.77635684e-15 -1.00000000e+00]

Eigenvectors:
[[0.5547002  0.4472136 ]
 [0.83205029 0.89442719]]


In [1]:
#Q3. generate all the prime numbers between 1 to 100 using python code.
for i in range(1,101):
    count=0
    for j in range(1,i+1):
        if (i%j)==0:
            count=count+1
    if(count==2):
        print(i)
        


2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [19]:
# Q.3 a. 1.Write Python program to estimate the value of the integration sin(x)dx of limits 0 to pi using Simpson’s (1/3)rd rule (n=6).
import numpy as np

def f(x):
    """Function to integrate."""
    return np.sin(x)

def simpsons_rule(a, b, n):
    """Estimate the integral of f(x) from a to b using Simpson's (1/3) rule."""
    if n % 2 != 0:
        raise ValueError("n must be an even number.")
    
    h = (b - a) / n  # Step size
    integral = f(a) + f(b)  # f(a) + f(b)
    
    # Apply Simpson's rule
    for i in range(1, n, 2):
        integral += 4 * f(a + i * h)  # Odd indices
    
    for i in range(2, n-1, 2):
        integral += 2 * f(a + i * h)  # Even indices
    
    integral *= h / 3  # Final multiplication by h/3
    return integral

# Define the interval and number of subintervals
a = 0
b = np.pi
n = 6

# Estimate the integral
integral_value = simpsons_rule(a, b, n)

print(f"The estimated value of the integral ∫ sin(x) dx from 0 to π is: {integral_value:.6f}")


The estimated value of the integral ∫ sin(x) dx from 0 to π is: 2.000863


In [20]:
#Q.3a.2 write python program to evaluate third order forward difference of the given data 
# x  0 1 2 3    y=f(x) 1 0 1 10
import numpy as np

# Given data
X = np.array([0, 1, 2, 3])
Y = np.array([1, 0, 1, 10])

# Calculate forward differences
def forward_difference(Y):
    n = len(Y)
    # Create a table for storing differences
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = Y  # First column is original Y values

    # Calculate forward differences
    for j in range(1, n):
        for i in range(n - j):
            diff_table[i][j] = diff_table[i + 1][j - 1] - diff_table[i][j - 1]

    return diff_table

# Compute the forward difference table
diff_table = forward_difference(Y)

# Output the forward difference table
print("Forward Difference Table:")
for i in range(len(diff_table)):
    print(" | ".join(f"{diff_table[i][j]:.4f}" for j in range(len(diff_table[i])) if diff_table[i][j] != 0))


Forward Difference Table:
1.0000 | -1.0000 | 2.0000 | 6.0000
1.0000 | 8.0000
1.0000 | 9.0000
10.0000


In [21]:
#Q.3b.1 write python program to evaluate f93.5of the given data 
# x 1 2 3 4 5  y=f(x) 30 50 55 40 11
import numpy as np

# Given data points
X = np.array([1, 2, 3, 4, 5])
Y = np.array([30, 50, 55, 40, 11])

def linear_interpolation(x, x0, x1, y0, y1):
    """Perform linear interpolation."""
    return y0 + (y1 - y0) * (x - x0) / (x1 - x0)

def estimate_f(target_x):
    """Estimate the value of f(target_x) using linear interpolation."""
    # Check if target_x is within the range of X
    if target_x < X[0] or target_x > X[-1]:
        raise ValueError("Target x is out of bounds of the provided data.")

    # Find the interval for target_x
    for i in range(len(X) - 1):
        if X[i] <= target_x <= X[i + 1]:
            # Perform linear interpolation
            return linear_interpolation(target_x, X[i], X[i + 1], Y[i], Y[i + 1])
    
    return None  # Just in case we don't find a suitable interval

# Estimate f(3.5)
target_x = 3.5
estimated_value = estimate_f(target_x)

print(f"The estimated value of f({target_x}) is: {estimated_value:.4f}")


The estimated value of f(3.5) is: 47.5000


In [23]:
#Q.3b.2 write python program to estimate the value of the integral 2 to10 (1/(1+x))dx usiong traprzoidal rule (n=5)
import numpy as np

# Define the function to integrate
def f(x):
    return 1/(1 + x)

# Trapezoidal Rule implementation
def trapezoidal_rule(a, b, n):
    h = (b - a) / n  # Step size
    integral_value = 0.5 * (f(a) + f(b))  # Start with the endpoints

    # Calculate the area for each trapezoid
    for i in range(1, n):
        integral_value += f(a + i * h)

    integral_value *= h  # Final result
    return integral_value

# Set the limits of integration and the number of intervals
a = 2
b = 10
n = 5

# Estimate the integral
integral_result = trapezoidal_rule(a, b, n)
print(f"The estimated value of the integral from {a} to {b} for 1/(1 + x)dx using Trapezoidal rule is: {integral_result:.4f}")


The estimated value of the integral from 2 to 10 for 1/(1 + x)dx using Trapezoidal rule is: 1.3206
