# Practical 4 

In [1]:
#Q.1.1 using python code sort the tuple in ascending and descending order 5,-3,0,1,6,-6,2
numbers =(5,-3,0,1,6,-6,2)
ascending_order=tuple(sorted(numbers))
descending_order=tuple(sorted(numbers,reverse=True))
print(ascending_order)
print(descending_order)

(-6, -3, 0, 1, 2, 5, 6)
(6, 5, 2, 1, 0, -3, -6)


In [5]:
#Q.1.2 write python program which deals with concatenation and repeatition of lists 
#list1=[15,20,25,30,35,40]   list2=[7,14,21,28,35,42]
#a) find list1 +list2
#b) find 9*list1
#c) find 7*list2

list1=[15,20,25,30,35,40]
list2=[7,14,21,28,35,42]
a= list1+list2
b=9*list1
c=7*list2
print(a)
print(b)
print(c)

[15, 20, 25, 30, 35, 40, 7, 14, 21, 28, 35, 42]
[15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40, 15, 20, 25, 30, 35, 40]
[7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42, 7, 14, 21, 28, 35, 42]


In [8]:
#Q.1.3 write python program to find the square of odd numbers from 1to20 using whlie loop
i=1
while (i<=20):
    if i%2==0:
        pass
    else:
        a=i*i
        print (a)
    i=i+1

1
9
25
49
81
121
169
225
289
361


In [9]:
#Q.2.1 using python construct the following matrices:

import numpy as np

# 1. Create an identity matrix of order 10 x 10
identity_matrix = np.eye(10)
print("Identity Matrix (10x10):")
print(identity_matrix)

# 2. Create a zero matrix of order 7 x 3
zero_matrix = np.zeros((7, 3))
print("\nZero Matrix (7x3):")
print(zero_matrix)

# 3. Create a ones matrix of order 5 x 4
ones_matrix = np.ones((5, 4))
print("\nOnes Matrix (5x4):")
print(ones_matrix)

Identity Matrix (10x10):
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

Zero Matrix (7x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix (5x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
#Q.2.2 find the data type of the following daya by using python code:
# a. number  b. 31.25  c. 8+4j  d. Mathematics e. 49
a="number"
b= 31.25
c=8+4j
d= "Mathematics"
e=49
print("data type of ",a, "is ", type(a),"\ndata type of ",b,"is ",type(b),"\ndata type of ",c, "is ", type(c),"\ndata type of ", d, "is ",type(d),"\ndata type of ",e, "is ",type(e))

data type of  number is  <class 'str'> 
data type of  31.25 is  <class 'float'> 
data type of  (8+4j) is  <class 'complex'> 
data type of  Mathematics is  <class 'str'> 
data type of  49 is  <class 'int'>


In [15]:
#Q.2.3 write python program to find the determinant of matrices A=[1 0 5 ; 2 1 6 : 3 4 0] and B=[2 5 : -1 4]
import numpy as np
# define a matrix
A= np.array([[1,0,5],[2,1,6],[3,4,0]])
B=np.array([[2,5],[-1,4]])
# calculate the determinant
detA =np.linalg.det(A)
detB =np.linalg.det(B)
print("A=",A)
print("B=",B)
print("Determinant of matrix A is ", detA,"\nDeterminant of matrix B is ",detB)


A= [[1 0 5]
 [2 1 6]
 [3 4 0]]
B= [[ 2  5]
 [-1  4]]
Determinant of matrix A is  0.9999999999999967 
Determinant of matrix B is  13.0


In [16]:
#Q3.a.1 write python program to estimate the value of the integral xsin(x) dx from 0 to pi using simpson's (1/3)rd rule (n=6)

import numpy as np

def f(x):
    """Define the function to be integrated."""
    return x * np.sin(x)

def simpsons_rule(a, b, n):
    """Estimate the integral of f(x) from a to b using Simpson's (1/3) rule."""
    if n % 2 != 0:
        raise ValueError("n must be an even number.")
    
    h = (b - a) / n  # Step size
    integral = f(a) + f(b)  # f(a) + f(b)
    
    # Sum the odd indices
    for i in range(1, n, 2):
        integral += 4 * f(a + i * h)
    
    # Sum the even indices
    for i in range(2, n, 2):
        integral += 2 * f(a + i * h)
    
    integral *= h / 3  # Final result
    return integral

# Set the limits and number of intervals
a = 0
b = np.pi
n = 6

# Estimate the integral
result = simpsons_rule(a, b, n)
print(f"The estimated value of the integral from {a} to {b} is: {result:.6f}")


The estimated value of the integral from 0 to 3.141592653589793 is: 3.142949


In [18]:
#Q.3.a.2 write the python program to estimate the root of an equation f(x)=3x-cos(x)-1 using newton raphson method correct upto four decimal places.

import numpy as np

def f(x):
    """Define the function for which we want to find the root."""
    return 3 * x - np.cos(x) - 1

def f_prime(x):
    """Define the derivative of the function."""
    return 3 + np.sin(x)

def newton_raphson(initial_guess, tolerance=1e-4, max_iterations=100):
    """Approximate the root of the function using the Newton-Raphson method."""
    x_n = initial_guess

    for iteration in range(max_iterations):
        x_n1 = x_n - f(x_n) / f_prime(x_n)  # Newton-Raphson formula

        # Check for convergence
        if abs(x_n1 - x_n) < tolerance:
            print(f"Root found: x = {x_n1:.4f} in {iteration + 1} iterations")
            return x_n1
        
        x_n = x_n1

    print("Max iterations reached without finding a root.")
    return None

# Initial guess for the root
initial_guess = 0.5

# Call the newton_raphson function to find the root
root = newton_raphson(initial_guess)



Root found: x = 0.6071 in 3 iterations


In [19]:
#Q.3.b.1 write the python program to find all positive prime numbers less than givan number n.

def is_prime(num):
    """Check if a number is prime."""
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def find_primes(n):
    """Find all prime numbers less than n."""
    primes = []
    for num in range(2, n):  # Start from 2 since 1 is not prime
        if is_prime(num):
            primes.append(num)
    return primes

# Input: Get a number from the user
n = int(input("Enter a positive integer n: "))

# Find and print all prime numbers less than n
primes = find_primes(n)
print(f"Prime numbers less than {n}: {primes}")


Enter a positive integer n: 48
Prime numbers less than 48: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


In [21]:
#Q.3b.2 write the python program to evaluate f(2.5)by forward difference formula of given data.
# x  0 1 2 3  y=f(x) 2 1 2 10
import numpy as np

# Given data points
X = np.array([0, 1, 2, 3])
Y = np.array([2, 1, 2, 10])

# Calculate forward differences
def forward_differences(Y):
    n = len(Y)
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = Y  # First column is the original values
    
    # Fill in the forward difference table
    for j in range(1, n):
        for i in range(n - j):
            diff_table[i][j] = diff_table[i + 1][j - 1] - diff_table[i][j - 1]
    
    return diff_table

# Evaluate f(x) using forward difference formula
def evaluate_forward_difference(x, X, Y, diff_table):
    n = len(X)
    h = X[1] - X[0]  # Assuming uniform spacing
    k = (x - X[0]) / h  # Position in the forward difference table
    
    result = Y[0]  # f(x0)
    
    # Using forward difference coefficients
    for j in range(1, n):
        term = diff_table[0][j] * np.prod([(k - i) for i in range(j)]) / np.math.factorial(j)
        result += term
    
    return result

# Calculate forward difference table
diff_table = forward_differences(Y)

# Value at which to evaluate
x_value = 2.5

# Evaluate f(2.5)
estimated_value = evaluate_forward_difference(x_value, X, Y, diff_table)
print(f"The estimated value of f(2.5) is: {estimated_value:.4f}")


The estimated value of f(2.5) is: 4.8125
