# Practical 5

In [24]:
#Q.1.1 Using sympy module of python find the following for the matrices:
# A =[-1 1 0  ; 8 5 2  ; 2 -6 2] and B= [9 0 3  ; 1 4 1  ;1 0 -1]
import sympy as sy
sy.init_printing()
A=sy.Matrix([[-1,1,0],[8,5,2],[2,-6,2]])
B=sy.Matrix([[9,0,3],[1,4,1],[1,0,-1]])

A ,B


⎛⎡-1  1   0⎤  ⎡9  0  3 ⎤⎞
⎜⎢         ⎥  ⎢        ⎥⎟
⎜⎢8   5   2⎥, ⎢1  4  1 ⎥⎟
⎜⎢         ⎥  ⎢        ⎥⎟
⎝⎣2   -6  2⎦  ⎣1  0  -1⎦⎠

In [25]:
#a) 2A+B

2*A+B


⎡7    2   3⎤
⎢          ⎥
⎢17  14   5⎥
⎢          ⎥
⎣5   -12  3⎦

In [17]:
#b) 3A-5B
3*A-5*B

⎡-48   3   -15⎤
⎢             ⎥
⎢19   -5    1 ⎥
⎢             ⎥
⎣ 1   -18  11 ⎦

In [18]:
#c) A^-1  (inverse of A)
A.inv()

⎡-11              ⎤
⎢────  1/17  -1/17⎥
⎢ 17              ⎥
⎢                 ⎥
⎢6/17  1/17  -1/17⎥
⎢                 ⎥
⎢ 29          13  ⎥
⎢ ──   2/17   ──  ⎥
⎣ 17          34  ⎦

In [29]:
#d) B^3
B**3

⎡780  0   228⎤
⎢            ⎥
⎢148  64  52 ⎥
⎢            ⎥
⎣76   0   20 ⎦

In [26]:
#e) (transpose of A + transpose of B) =A^T+B^T
A.T +B.T

⎡8  9  3 ⎤
⎢        ⎥
⎢1  9  -6⎥
⎢        ⎥
⎣3  3  1 ⎦

In [32]:
#Q.1.2 Evaluate following expression on python 
#a) M=[1,2,3,4]. Find length of M
M=[1,2,3,4]
print(len(M))

#b) L="XYZ"+"pqr". find L
L="XYZ"+"pqr"
print(L)

#c) s='Make In India', find (s[:7])& (s[:9])
s="Make In India"
print(s[:7])
print(s[:9])

4
XYZpqr
Make In
Make In I


In [33]:
#Q.1.3 use python code to generate the square root of numbers from 21 to 49.
import math
for i in range(21,50):
    print(math.sqrt(i))
    i=i+1

4.58257569495584
4.69041575982343
4.795831523312719
4.898979485566356
5.0
5.0990195135927845
5.196152422706632
5.291502622129181
5.385164807134504
5.477225575051661
5.5677643628300215
5.656854249492381
5.744562646538029
5.830951894845301
5.916079783099616
6.0
6.082762530298219
6.164414002968976
6.244997998398398
6.324555320336759
6.4031242374328485
6.48074069840786
6.557438524302
6.6332495807108
6.708203932499369
6.782329983125268
6.855654600401044
6.928203230275509
7.0


In [34]:
# Q.2) Attempt th following:
# 1. Using python code construct the following matrices.
#  1)An identity matrix of order 10 x 10

import numpy as np
np.array(np.identity(10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
# 2) zero matrix of order 7 x 3

import numpy as np
np.zeros([7,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# 3) Ones matrix of order 5 x 4
import numpy as np
np.ones([5,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
#Q.2.2 using linsolve command in python, solve the following system of linear equations:
# x-2y+3z=7  ;  2x+y+z=4  ; -3x+2y-2z=-10
import sympy as sy
x =sy.symbols('x')
y =sy.symbols('y')
z =sy.symbols('z')

EQN1=sy.Eq(x - 2*y +3*z,7)
EQN2=sy.Eq(2*x + y +z ,4)
EQN3=sy.Eq(-3*x +2*y - 2*z,-10)

system = [EQN1,EQN2,EQN3]
solnSet =sy.linsolve(system,x,y,z)
solnSet

In [50]:
#Q.2.3 Generate all relatively prime numbers to 111 which are less than 150 using python code.
import math

num=111
for i in range (1,150):
    if math.gcd(i,111)==1:
        print(i)
        
    else :
        pass
    i=i+1

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
38
40
41
43
44
46
47
49
50
52
53
55
56
58
59
61
62
64
65
67
68
70
71
73
76
77
79
80
82
83
85
86
88
89
91
92
94
95
97
98
100
101
103
104
106
107
109
110
112
113
115
116
118
119
121
122
124
125
127
128
130
131
133
134
136
137
139
140
142
143
145
146
149


In [67]:
#Q.3a.1. write the python code to find eigenvalues and corresponding vectors of the matrix . A=[1 3 3  ;2 2 3  ;4 2 1] and hence find matrix P with diagonalize to A
import numpy as np

# Define the matrix A
A = np.array([[1, 3, 3],
              [2, 2, 3],
              [4, 2, 1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, P = np.linalg.eig(A)

# Create a diagonal matrix D from the eigenvalues
D = np.diag(eigenvalues)

# Print the results
print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nMatrix P (eigenvectors):")
print(P)
print("\nDiagonal Matrix D (eigenvalues):")
print(D)

# Verify the diagonalization: A = P * D * P_inv
P_inv = np.linalg.inv(P)
A_reconstructed = P @ D @ P_inv
print("\nReconstructed Matrix A from P, D:")
print(A_reconstructed)


Matrix A:
[[1 3 3]
 [2 2 3]
 [4 2 1]]

Eigenvalues:
[ 7. -2. -1.]

Matrix P (eigenvectors):
[[-5.77350269e-01 -4.08248290e-01  1.11022302e-16]
 [-5.77350269e-01 -4.08248290e-01 -7.07106781e-01]
 [-5.77350269e-01  8.16496581e-01  7.07106781e-01]]

Diagonal Matrix D (eigenvalues):
[[ 7.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -1.]]

Reconstructed Matrix A from P, D:
[[1. 3. 3.]
 [2. 2. 3.]
 [4. 2. 1.]]


In [68]:
#Q.3a.2 write the python code to estimate the root of f(x)=3x^2+4x-10 using newton raphson method correcr upto four demical places. 

def f(x):
    """Define the function for which we want to find the root."""
    return 3 * x**2 + 4 * x - 10

def f_prime(x):
    """Define the derivative of the function."""
    return 6 * x + 4

def newton_raphson(initial_guess, tolerance=1e-4, max_iterations=100):
    """Approximate the root of the function using the Newton-Raphson method."""
    x_n = initial_guess

    for iteration in range(max_iterations):
        x_n1 = x_n - f(x_n) / f_prime(x_n)  # Newton-Raphson formula

        # Check for convergence
        if abs(x_n1 - x_n) < tolerance:
            print(f"Root found: x = {x_n1:.4f} in {iteration + 1} iterations")
            return x_n1
        
        x_n = x_n1

    print("Max iterations reached without finding a root.")
    return None

# Initial guess for the root
initial_guess = 1.0

# Call the newton_raphson function to find the root
root = newton_raphson(initial_guess)


Root found: x = 1.2770 in 4 iterations


In [69]:
#Q3.b1.  write python programm to obtain the approximate real root of x^3-4x-9=0 by using regula falsi method.

def f(x):
    """Define the function for which we want to find the root."""
    return x**3 - 4*x - 9

def regula_falsi(x0, x1, tolerance=1e-6, max_iterations=100):
    """Approximate the root of the function using the Regula-Falsi method."""
    if f(x0) * f(x1) >= 0:
        print("The function has the same signs at the endpoints. Choose different points.")
        return None

    for iteration in range(max_iterations):
        # Calculate the root using the Regula-Falsi formula
        x2 = x1 - (f(x1) * (x0 - x1)) / (f(x0) - f(x1))
        
        # Check if the current approximation is close enough to the root
        if abs(f(x2)) < tolerance:
            print(f"Root found: x = {x2:.6f} in {iteration + 1} iterations")
            return x2
        
        # Update the interval
        if f(x0) * f(x2) < 0:
            x1 = x2  # The root is in the left subinterval
        else:
            x0 = x2  # The root is in the right subinterval

    print("Max iterations reached without finding a root.")
    return None

# Define the initial interval [2, 3]
x0 = 2
x1 = 3

# Call the regula_falsi function to find the root
root = regula_falsi(x0, x1)


Root found: x = 2.706528 in 8 iterations


In [72]:
#b.2write the python program to evaluate f(3.5) by forward differences of the given data :
# x  1 2 3 4 5    y=f(x)  41 62 65 50 17

import numpy as np

# Given data points
X = np.array([1, 2, 3, 4, 5])
Y = np.array([41, 62, 65, 50, 17])

# Calculate forward differences
def forward_differences(Y):
    n = len(Y)
    # Create a table for forward differences
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = Y
    
    for j in range(1, n):
        for i in range(n - j):
            diff_table[i][j] = diff_table[i + 1][j - 1] - diff_table[i][j - 1]
    
    return diff_table

# Calculate forward difference table
diff_table = forward_differences(Y)

# Function to evaluate f(x) using forward difference
def evaluate_forward_difference(x, X, Y, diff_table):
    n = len(X)
    h = X[1] - X[0]  # Assuming uniform spacing
    k = (x - X[0]) / h  # k is the position in the forward difference table
    
    # Calculate the value of f(x) using the forward difference formula
    result = Y[0]  # f(x0)
    
    # Using forward difference coefficients
    for j in range(1, n):
        term = diff_table[0][j] * np.prod([(k - i) for i in range(j)]) / np.math.factorial(j)
        result += term
    
    return result

# Value at which to evaluate
x_value = 3.5

# Evaluate f(3.5)
estimated_value = evaluate_forward_difference(x_value, X, Y, diff_table)
print(f"The estimated value of f(3.5) is: {estimated_value:.4f}")



The estimated value of f(3.5) is: 59.7500
