# Practical 6

In [1]:
#Q.1.1 Use python code to evaluate each of the following expression.
#a) 23 modulus 2 +9-(3+7)x10 /2

a= 23%2+9-(3+7)*10/2
print(a)

#b) 35x10 floor division 3+15 modulus 3
b= 35*10//3+15%3
print(b)

#c) 3^5 -2^5 +4 floor division 7
c=3**5-2**5+4//7
print(c)

-40.0
116
211


In [19]:
#Q1.3 write the python program to find the maximum and minimum element in the list[7,8,71,32,49,-5,7,7,0,1,6]
list=[7,8,71,32,49,-5,7,7,0,1,6]
print(max(list))

print(min(list))



71
-5


In [21]:
#Q.2.1.using python code construct identity matrix of order 10 and find determinant ,trace and transpose of it
import sympy as sy
sy.init_printing()
A=sy.eye(10)
A


/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBa

⎡1  0  0  0  0  0  0  0  0  0⎤
⎢                            ⎥
⎢0  1  0  0  0  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  1  0  0  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  1  0  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  1  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  1  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  0  1  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  0  0  1  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  0  0  0  1  0⎥
⎢                            ⎥
⎣0  0  0  0  0  0  0  0  0  1⎦

In [22]:
A.det()

In [23]:
A.trace()

In [24]:
A.T

⎡1  0  0  0  0  0  0  0  0  0⎤
⎢                            ⎥
⎢0  1  0  0  0  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  1  0  0  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  1  0  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  1  0  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  1  0  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  0  1  0  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  0  0  1  0  0⎥
⎢                            ⎥
⎢0  0  0  0  0  0  0  0  1  0⎥
⎢                            ⎥
⎣0  0  0  0  0  0  0  0  0  1⎦

In [26]:
#Q.2.2 Write python code to find value the function f(x,y)=x^2-2xy+4 at poits (2,0) (1,-1)
def f(x,y):
        return x**2-2*x*y+4
print(f(2,0))
print(f(1,-1))


8
7


In [32]:
#Q.2.3 find numbers between 1 to 200 which are divisible by 7 using python code.
s=[]
for i in range (1,201):
    if i%7==0:
        s.append(i)
    else:
        pass
    i=i+1
print("numbers which are divisible by 7 between 1 to 200 : ",s)

numbers which are divisible by 7 between 1 to 200 :  [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196]


In [34]:
#Q.3.1 write python program to find the value of integral (x- sin(x))dx from 0 to pi using simpson's 1/3rd rule.(n=5)

import numpy as np

def f(x):
    return x - np.sin(x)

def simpsons_rule(a, b, n):
    if n % 2 != 0:
        raise ValueError("n must be an even number for Simpson's (1/3) rule.")
    
    h = (b - a) / n
    integral = f(a) + f(b)
    
    # Apply Simpson's (1/3) rule formula
    for i in range(1, n):
        x = a + i * h
        if i % 2 == 0:
            integral += 2 * f(x)
        else:
            integral += 4 * f(x)
    
    integral *= h / 3
    return integral

# Define the interval [a, b] and number of subintervals n
a = 0
b = np.pi
n = 5  # Number of subintervals (must be even)

# Calculate the integral using Simpson's (1/3)rd rule
# Since n is not even, let's correct it to 6 for the calculation.
n = 6
result = simpsons_rule(a, b, n)
print(f"The estimated value of the integral is: {result:.6f}")



The estimated value of the integral is: 2.933939


In [35]:
#Q.3.2 write python code to diagonalize matrix A=[3 -2  ; 6 -4] And find matrix P with diagonalise of A and diagonal matrix D
import numpy as np

# Define the matrix A
A = np.array([[3, -2],
              [6, -4]])

# Find the eigenvalues and right eigenvectors of A
eigenvalues, P = np.linalg.eig(A)

# Create the diagonal matrix D from the eigenvalues
D = np.diag(eigenvalues)

# Print the results
print("Matrix A:")
print(A)
print("\nMatrix P (eigenvectors):")
print(P)
print("\nDiagonal Matrix D (eigenvalues):")
print(D)

# Verify the diagonalization: A = P * D * P_inv
P_inv = np.linalg.inv(P)
A_reconstructed = P @ D @ P_inv
print("\nReconstructed Matrix A from P, D:")
print(A_reconstructed)



Matrix A:
[[ 3 -2]
 [ 6 -4]]

Matrix P (eigenvectors):
[[0.5547002  0.4472136 ]
 [0.83205029 0.89442719]]

Diagonal Matrix D (eigenvalues):
[[ 1.77635684e-15  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00]]

Reconstructed Matrix A from P, D:
[[ 3. -2.]
 [ 6. -4.]]


In [36]:
#Q.3b.1 write python code to find real root of x^3-2x-5=0 in[2,3] using regula falsi method

def f(x):
    """Define the function for which we want to find the root."""
    return x**3 - 2*x - 5

def regula_falsi(x0, x1, tolerance=1e-6, max_iterations=100):
    """Approximate the root of the function using the Regula-Falsi method."""
    if f(x0) * f(x1) >= 0:
        print("The function has the same signs at the endpoints. Choose different points.")
        return None

    for iteration in range(max_iterations):
        # Calculate the root using the Regula-Falsi formula
        x2 = x1 - (f(x1) * (x0 - x1)) / (f(x0) - f(x1))
        
        # Check if the current approximation is close enough to the root
        if abs(f(x2)) < tolerance:
            print(f"Root found: x = {x2:.6f} in {iteration + 1} iterations")
            return x2
        
        # Update the interval
        if f(x0) * f(x2) < 0:
            x1 = x2  # The root is in the left subinterval
        else:
            x0 = x2  # The root is in the right subinterval

    print("Max iterations reached without finding a root.")
    return None

# Define the interval [2, 3]
x0 = 2
x1 = 3

# Call the regula_falsi function to find the root
root = regula_falsi(x0, x1)


Root found: x = 2.094551 in 14 iterations


In [37]:
#Q3b.2 write python code to find the value of integral 1/(1+x) dx from 1 to5 using trapezoidal rule (n=10)

def f(x):
    """Define the function for which we want to integrate."""
    return 1 / (1 + x)

def trapezoidal_rule(a, b, n):
    """Estimate the integral of f from a to b using the Trapezoidal rule."""
    h = (b - a) / n  # Step size
    integral = (f(a) + f(b)) / 2  # Initialize with the first and last terms

    # Sum the function values at the interior points
    for i in range(1, n):
        x = a + i * h
        integral += f(x)

    integral *= h  # Multiply by the step size
    return integral

# Define the interval [1, 5] and number of subintervals n
a = 1
b = 5
n = 10  # Number of subintervals

# Calculate the integral using the trapezoidal rule
result = trapezoidal_rule(a, b, n)
print(f"The estimated value of the integral from {a} to {b} is: {result:.6f}")


The estimated value of the integral from 1 to 5 is: 1.101562
