# Practical 12

In [1]:
#Q.1.1. Use python code to evaluate each of the following expression.
# a. 20 modulus 2 +7 - (3+7)  * 10 /2
a= 20%2+7-(3+7)*10/2
print('a = ', a)

# b. 35 x 10 floor division 3 +15 modulus 3
b= 35*10//3+15%3
print('b = ',b)

# c. 3^5 -2^5 +4 floor division 7
c = 3**5 - 2**5 + 4//7
print ('c = ', c)




a =  -43.0
b =  116
c =  211


In [5]:
#Q.1.3 matrix A=[1 0 5 4  ; 2 1 6 -1  ; 3 4 0 2] Apply opration using python


import sympy as sy
sy.init_printing()
A= sy.Matrix([[1 ,0, 5, 4],[2, 1, 6, -1],[3 ,4 ,0 ,2]])
#a) delete 2nd row
A.row_del(1)
A

⎡1  0  5  4⎤
⎢          ⎥
⎣3  4  0  2⎦

In [6]:
#b) delete 1st column
A.col_del(0)
A

⎡0  5  4⎤
⎢       ⎥
⎣4  0  2⎦

In [12]:
# c) add column [9,9] as 2nd column

A=A.col_insert(1,sy.Matrix([9,9]))
A

⎡0  9  5  4⎤
⎢          ⎥
⎣4  9  0  2⎦

In [19]:
#Q.2.1 using python, find eigenvalues and corresponding eigenvectors of the matrix  
# A=[1 3 3  ;2 2 3  ;4 2 1]

import sympy as sy
sy.init_printing()
A= sy.Matrix([[1,3,3],[2,2,3],[4,2,1]])
print("eigenvalues = ",A.eigenvals())



eigenvalues =  {7: 1, -1: 1, -2: 1}


In [20]:
A.eigenvects()

⎡⎛       ⎡⎡-1/2⎤⎤⎞  ⎛       ⎡⎡0 ⎤⎤⎞  ⎛      ⎡⎡1⎤⎤⎞⎤
⎢⎜       ⎢⎢    ⎥⎥⎟  ⎜       ⎢⎢  ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟⎥
⎢⎜-2, 1, ⎢⎢-1/2⎥⎥⎟, ⎜-1, 1, ⎢⎢-1⎥⎥⎟, ⎜7, 1, ⎢⎢1⎥⎥⎟⎥
⎢⎜       ⎢⎢    ⎥⎥⎟  ⎜       ⎢⎢  ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟⎥
⎣⎝       ⎣⎣ 1  ⎦⎦⎠  ⎝       ⎣⎣1 ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

In [22]:
#Q.2.2 write python code to find product of n natural numbers using while loop
n=int(input("enter number:"))
i=1
num=1
while i<=n:
    num=num*i
    i=i+1
print("product of ",n, "natural number is ",num)

enter number:15
product of  15 natural number is  1307674368000


In [23]:
#Q.2.3 Generate all the prime numbers 1 to200 using python code.
for i in range(1,201):
    count=0
    for j in range(1,i+1):
        if (i%j)==0:
            count=count+1
    if(count==2):
        print(i)
        

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199


In [24]:
#Q.3 Write Python program to estimate the value of the integral integrate sin(x) dx from 0 to pi using Simp- son's (1/3) ^ (rd) rule (n = 6) .

import numpy as np

def f(x):
    """Function to integrate."""
    return np.sin(x)

def simpsons_rule(a, b, n):
    """Estimate the integral of f(x) from a to b using Simpson's (1/3) rule."""
    if n % 2 != 0:
        raise ValueError("n must be an even number.")
    
    h = (b - a) / n  # Step size
    integral = f(a) + f(b)  # f(a) + f(b)
    
    # Apply Simpson's rule
    for i in range(1, n, 2):
        integral += 4 * f(a + i * h)  # Odd indices
    
    for i in range(2, n-1, 2):
        integral += 2 * f(a + i * h)  # Even indices
    
    integral *= h / 3  # Final multiplication by h/3
    return integral

# Define the interval and number of subintervals
a = 0
b = np.pi
n = 6

# Estimate the integral
integral_value = simpsons_rule(a, b, n)

print(f"The estimated value of the integral ∫ sin(x) dx from 0 to π is: {integral_value:.6f}")


The estimated value of the integral ∫ sin(x) dx from 0 to π is: 2.000863


In [27]:
#Q3 Write Python code to find eigenvalues and corresponding eigenvectors of the matrix A=[3 -2  ;6 -4 ] and hence find matrix P with diagonalize to A.
import numpy as np

# Define the matrix A
A = np.array([[3,-2],
              [6,-4]])

# Calculate eigenvalues and eigenvectors
eigenvalues, P = np.linalg.eig(A)

# Create a diagonal matrix D from the eigenvalues
D = np.diag(eigenvalues)

# Print the results
print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nMatrix P (eigenvectors):")
print(P)
print("\nDiagonal Matrix D (eigenvalues):")
print(D)

# Verify the diagonalization: A = P * D * P_inv
P_inv = np.linalg.inv(P)
A_reconstructed = P @ D @ P_inv
print("\nReconstructed Matrix A from P, D:")
print(A_reconstructed)


Matrix A:
[[ 3 -2]
 [ 6 -4]]

Eigenvalues:
[ 1.77635684e-15 -1.00000000e+00]

Matrix P (eigenvectors):
[[0.5547002  0.4472136 ]
 [0.83205029 0.89442719]]

Diagonal Matrix D (eigenvalues):
[[ 1.77635684e-15  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00]]

Reconstructed Matrix A from P, D:
[[ 3. -2.]
 [ 6. -4.]]


In [28]:
#Q3b Write Python program to obtained the approximate real roots of x ^ 3 - 2x - 5 = 0 in [2,3] using Regula-falsi method

def f(x):
    return x**3 - 2*x - 5

def regula_falsi(x0, x1, tolerance=1e-7, max_iterations=100):
    if f(x0) * f(x1) >= 0:
        print("The function has the same signs at the endpoints. No root found.")
        return None

    for i in range(max_iterations):
        # Calculate the point where the line crosses the x-axis
        x2 = x1 - (f(x1) * (x1 - x0)) / (f(x1) - f(x0))

        # Check if the root is found or if it is within the tolerance
        if abs(f(x2)) < tolerance:
            return x2

        # Update the points based on the sign of the function
        if f(x2) * f(x0) < 0:
            x1 = x2  # Root is in the left subinterval
        else:
            x0 = x2  # Root is in the right subinterval

    print("Maximum iterations reached. No root found.")
    return None

# Set the interval [2, 3]
x0 = 2
x1 = 3

# Finding the root
root = regula_falsi(x0, x1)

if root is not None:
    print(f"The approximate real root of the equation in [{x0}, {x1}] is: {root:.6f}")


The approximate real root of the equation in [2, 3] is: 2.094551


In [29]:
#Q.3b2  Write a Python program to estimate the value of the integral 1 to 5 (1/ (1+x))  dx using Trape-zoidal rule (n=10).

def f(x):
    """Define the function for which we want to integrate."""
    return 1 / (1 + x)

def trapezoidal_rule(a, b, n):
    """Estimate the integral of f from a to b using the Trapezoidal rule."""
    h = (b - a) / n  # Step size
    integral = (f(a) + f(b)) / 2  # Initialize with the first and last terms

    # Sum the function values at the interior points
    for i in range(1, n):
        x = a + i * h
        integral += f(x)

    integral *= h  # Multiply by the step size
    return integral

# Define the interval [1, 5] and number of subintervals n
a = 1
b = 5
n = 10  # Number of subintervals

# Calculate the integral using the trapezoidal rule
result = trapezoidal_rule(a, b, n)
print(f"The estimated value of the integral from {a} to {b} is: {result:.6f}")


The estimated value of the integral from 1 to 5 is: 1.101562
